import FormalVerification.BasicDefinitions
import FormalVerification.PublicStates
import FormalVerification.Kitagawa
import FormalVerification.CompositionOnly
import FormalVerification.BridgeProduct
import FormalVerification.Frechet
import FormalVerification.QueueFlow
import FormalVerification.IdentifiedSets
import FormalVerification.DVClassification
import FormalVerification.SelectionBounds
import FormalVerification.PriorityHistory
import FormalVerification.WitnessDeletion
import FormalVerification.Regularization
import FormalVerification.DeterministicTransform
import FormalVerification.Standardization
import FormalVerification.JointMass
import FormalVerification.WitnessRegimes
import FormalVerification.SetPropagation

-- Kernel-dependency audit. These commands are also run directly by the
-- verification gate and their output is summarized in VERIFICATION_REPORT.md.
#print axioms FormalVerification.UnitInterval.nonneg
#print axioms FormalVerification.UnitInterval.le_one
#print axioms FormalVerification.PublicStates.indicator_sum_one
#print axioms FormalVerification.PublicStates.indicators_mutually_exclusive
#print axioms FormalVerification.PublicStates.realized_state_unique
#print axioms FormalVerification.Kitagawa.symmetric_identity
#print axioms FormalVerification.Kitagawa.finite_symmetric_identity
#print axioms FormalVerification.CompositionOnly.sign_nonnegative
#print axioms FormalVerification.CompositionOnly.negative_sign_rejects_composition_only
#print axioms FormalVerification.CompositionOnly.boundary_q_zero
#print axioms FormalVerification.CompositionOnly.boundary_q_one
#print axioms FormalVerification.CompositionOnly.dropped_unit_interval_counterexample
#print axioms FormalVerification.BridgeProduct.admissible_factorization
#print axioms FormalVerification.BridgeProduct.distinct_endpoint_factorizations
#print axioms FormalVerification.BridgeProduct.one_product_forces_factors_one
#print axioms FormalVerification.BridgeProduct.positive_internal_zero_product
#print axioms FormalVerification.BridgeProduct.zero_internal_gives_zero_product
#print axioms FormalVerification.BridgeProduct.zero_internal_conditioning_cell_undefined
#print axioms FormalVerification.Frechet.overlap_bounds
#print axioms FormalVerification.Frechet.conditional_overlap_bounds
#print axioms FormalVerification.Frechet.marginals_normalized
#print axioms FormalVerification.Frechet.lower_endpoint_attainable
#print axioms FormalVerification.Frechet.upper_endpoint_attainable
#print axioms FormalVerification.QueueFlow.total_exits_identified
#print axioms FormalVerification.QueueFlow.positive_total_has_distinct_splits
#print axioms FormalVerification.QueueFlow.zero_total_split_unique
#print axioms FormalVerification.QueueFlow.bridge_does_not_identify_queue_state
#print axioms FormalVerification.QueueFlow.empty_stock_flow_set
#print axioms FormalVerification.QueueFlow.total_exit_outer_bounds
#print axioms FormalVerification.IdentifiedSets.witness_contraction
#print axioms FormalVerification.IdentifiedSets.diameter_at_most_mono
#print axioms FormalVerification.IdentifiedSets.inclusion_minimal_of_deletion_tests
#print axioms FormalVerification.DVClassification.declared_rule_lower_bound
#print axioms FormalVerification.DVClassification.declared_rule_upper_bound
#print axioms FormalVerification.DVClassification.lower_endpoint_attainable
#print axioms FormalVerification.DVClassification.upper_endpoint_attainable
#print axioms FormalVerification.DVClassification.every_integer_attainable
#print axioms FormalVerification.SelectionBounds.sharp_binary_mixture_bounds
#print axioms FormalVerification.SelectionBounds.lower_endpoint_attainable
#print axioms FormalVerification.SelectionBounds.upper_endpoint_attainable
#print axioms FormalVerification.SelectionBounds.every_point_attainable
#print axioms FormalVerification.PriorityHistory.endpoint_disagreement_implies_change
#print axioms FormalVerification.PriorityHistory.stable_equal_endpoint_completion
#print axioms FormalVerification.PriorityHistory.offsetting_equal_endpoint_completion
#print axioms FormalVerification.PriorityHistory.endpoint_event_subset_history_event
#print axioms FormalVerification.WitnessDeletion.clock_marginals_do_not_identify_duration_distribution
#print axioms FormalVerification.WitnessDeletion.lineage_marginals_do_not_identify_eligible_completion
#print axioms FormalVerification.Regularization.feasible_set_not_singleton
#print axioms FormalVerification.Regularization.zero_is_unique_regularized_selector
#print axioms FormalVerification.DeterministicTransform.deterministic_transform_is_redundant
#print axioms FormalVerification.DeterministicTransform.cross_regime_equality_of_equal_base
#print axioms FormalVerification.DeterministicTransform.determinism_alone_does_not_imply_cross_regime_equality
#print axioms FormalVerification.Standardization.standardized_simplex
#print axioms FormalVerification.Standardization.standardized_contrast_sums_to_zero
#print axioms FormalVerification.Standardization.omitted_state_determined
#print axioms FormalVerification.JointMass.joint_masses_recover_recorded_mass
#print axioms FormalVerification.JointMass.conditional_share_recovered_from_joint_mass
#print axioms FormalVerification.JointMass.joint_mass_change_equals_kitagawa_terms
#print axioms FormalVerification.WitnessRegimes.legal_queue_priority_pair_count
#print axioms FormalVerification.WitnessRegimes.witness_regime_count
#print axioms FormalVerification.SetPropagation.tagged_union_membership
#print axioms FormalVerification.SetPropagation.true_pair_belongs_to_propagated_region
#print axioms FormalVerification.SetPropagation.next_reachable_membership
#print axioms FormalVerification.PriorityHistory.endpoint_probability_le_history_probability
#print axioms FormalVerification.SelectionBounds.unavailable_coverage_leaves_unit_interval
